export const productApi = [
     { id: 1,
    image: '/assetes/showcase-img-1.jpg',
    name: "Bag"
  },
  { id: 2,
    image: '/assetes/showcase-img-2.jpg',
    name: "Oction" 
  },
  { id: 3,
    image: '/assetes/showcase-img-3.jpg',
    name: "Bag"
  },
  { id: 4,
    image: '/assetes/showcase-img-4.jpg',
    name: "Cap" 
  },
  { id: 5,  
    image: '/assetes/showcase-img-5.jpg',
    name: "Shirt" 
  },
  { id: 6,
    image: '/assetes/showcase-img-6.jpg',
    name: "Pattern Shirt" 

  },
  { id: 7, 
    image: '/assetes/showcase-img-7.jpg',
    name: "Shose"

   },
  { id: 8,
     image: '/assetes/showcase-img-8.jpg',
     name: "Bag" 

  },
  {
    id: 9,
    name: "Colorfull Patter Shirt",
    image: "/assetes/product-1-1.jpg",
    image2: "/assetes/product-1-2.jpg",
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 10,
    name: "Designfull Patter Shirt",
    image: "/assetes/product-2-1.jpg",
    image2: "/assetes/product-2-2.jpg",
    rating: 2.4,
    price: "$134",
    oldPrice: "$234",
    category: "Cloath",
    title: "New",
  },
  {
    id: 11,
    name: "Bata Shose",
    image: "/assetes/product-3-1.jpg",
    image2: "/assetes/product-3-2.jpg",
    rating: 4.4,
    price: "$64",
    oldPrice: "$94",
    category: "Cloath",
    title: "15% off",
  },
  {
    id: 12,
    name: "White Skiny Trousor",
    image: "/assetes/product-4-1.jpg",
    image2: "/assetes/product-4-2.jpg",
    rating: 3.2,
    price: "$44",
    oldPrice: "$64",
    category: "Cloath",
    title: "55% off",
  },
  {
    id: 13,
    name: "Caps for womens",
    image: "/assetes/product-5-1.jpg",
    image2: "/assetes/product-5-2.jpg",
    rating: 2.4,
    price: "$34",
    oldPrice: "$54",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 14,
    name: "Blue Shirt for mens",
    image: "/assetes/product-6-1.jpg",
    image2: "/assetes/product-6-2.jpg",
    rating: 3,
    price: "$24",
    oldPrice: "$34",
    category: "Cloath",
    title: "New",
  },
  {
    id: 15,
    name: "Skiny White Shirt",
    image: "/assetes/product-7-1.jpg",
    image2: "/assetes/product-7-2.jpg",
    rating: 3.1,
    price: "$23",
    oldPrice: "$34",
    category: "Cloath",
    title: "55% off",
  },
  {
    id: 16,
    name: "Sandle for womens",
    image: "/assetes/product-8-1.jpg",
    image2: "/assetes/product-8-2.jpg",
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category: "Cloath",
    title: "New",
  },
  {
    id: 17,
    name: "White/Blue Trousor",
    image: "/assetes/product-9-1.jpg",
    image2: "/assetes/product-9-2.jpg",
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category: "Cloath",
    title: "New",
  },
  {
    id: 18,
    name: "Sandle for womens",
    image: "/assetes/product-10-1.jpg",
    image2: "/assetes/product-10-2.jpg",
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category: "Cloath",
    title: "New",
  },
  {
    id: 19,
    name: "White Trousor",
    image: "/assetes/product-11-1.jpg",
    image2: "/assetes/product-11-2.jpg",
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category: "Cloath",
    title: "New",
  },
  {
    id: 20,
    name: "Hand Bag for womens",
    image: "/assetes/product-13-1.jpg",
    image2: "/assetes/product-13-2.jpg",
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category: "Cloath",
    title: "New",
  },
   {
    id: 21,
    name: "White Patter Shirt",
    image: '/assetes/product-12-1.jpg',
    image2:'/assetes/product-12-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 22,
    name: "White/Blue Trousor",
    image: '/assetes/product-11-1.jpg',
    image2:'/assetes/product-11-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 23,
    name: "Sandle for womens",
    image: '/assetes/product-10-1.jpg',
    image2:'/assetes/product-10-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 24,
    name: "Skiny shirt for boys",
    image: '/assetes/product-9-1.jpg',
    image2:'/assetes/product-9-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 25,
    name: "Red/blue shirt",
    image: '/assetes/product-8-1.jpg',
    image2:'/assetes/product-8-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 26,
    name: "Blue Shirt",
    image: '/assetes/product-7-1.jpg',
    image2:'/assetes/product-7-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },

  {
    id: 27,
    name: "Colorfull Patter Shirt",
    image: '/assetes/product-6-1.jpg',
    image2:'/assetes/product-6-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 28,
    name: "Cap for womens",
    image: '/assetes/product-5-1.jpg',
    image2:'/assetes/product-5-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 29,
    name: "White Trousor",
    image: '/assetes/product-4-1.jpg',
    image2:'/assetes/product-4-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 30,
    name: "Bata shose for mens",
    image: '/assetes/product-3-1.jpg',
    image2:'/assetes/product-3-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 31,
    name: "Colorfull Patter Shirt",
    image: '/assetes/product-2-1.jpg',
    image2:'/assetes/product-2-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
  {
    id: 32,
    name: "Colorfull Patter Shirt",
    image: '/assetes/product-1-1.jpg',
    image2:'/assetes/product-1-2.jpg',
    rating: 3.4,
    price: "$234",
    oldPrice: "$334",
    category: "Cloath",
    title: "25% off",
  },
    {
    id: 33,
    name: "Green Yellow Shirt",
    image: '/assetes/product-2-1.jpg',
    image2:'/assetes/product-2-2.jpg',
    rating: 2.4,
    price: "$134",
    oldPrice: "$234",
    category:'Cloath',
    title:'New'
  },

  {
    id: 34,
    name: "Cap for men's",
    image: '/assetes/product-5-1.jpg',
    image2:'/assetes/product-5-2.jpg',
    rating: 3.2,
    price: "$44",
    oldPrice: "$64",
    category:'Cloath',
    title:'New'
  },

  {
    id: 35,
    name: "Red Yellow Shirt",
    image: '/assetes/product-8-1.jpg',
    image2:'/assetes/product-8-2.jpg',
    rating: 3,
    price: "$24",
    oldPrice: "$34",
    category:'Cloath',
    title:'New'
  },
  {
    id: 36,
    name: "Colorfull Patter Shirt",
    image: '/assetes/product-1-1.jpg',
    image2:'/assetes/product-1-2.jpg',
    rating: 3.1,
    price: "$23",
    oldPrice: "$34",
    category:'Cloath',
    title:'New'
  },
  {
    id: 37,
    name: "Skiny Trousor",
    image: '/assetes/product-4-1.jpg',
    image2:'/assetes/product-4-2.jpg',
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category:'Cloath',
    title:'New'
  },
   {
    id: 38,
    name: "Cap for men's",
   image: '/assetes/product-5-1.jpg',
    image2:'/assetes/product-5-2.jpg',
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category:'Cloath',
    title:'New'
  },
   {
    id: 39,
    name: "women's shirt",
    image: '/assetes/product-7-1.jpg',
    image2:'/assetes/product-7-2.jpg',
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category:'Cloath',
    title:'New'
  },
   {
    id: 40,
    name: "Colorfull Patter Shirt",
    image: '/assetes/product-9-1.jpg',
    image2:'/assetes/product-9-2.jpg',
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category:'Cloath',
    title:'New'
  },
   {
    id: 41,
    name: "White Shirt",
    image: '/assetes/product-12-1.jpg',
    image2:'/assetes/product-12-2.jpg',
    rating: 3.6,
    price: "$24",
    oldPrice: "$34",
    category:'Cloath',
    title:'New'
  },
]